import { useState, useEffect, useRef, useCallback } from 'react';
import { motion } from 'motion/react';
import { X, ExternalLink, FileText, Image, FileDown, ChevronDown, Loader2 } from 'lucide-react';
import { fetchToolResult } from '../lib/supabase';
import { auth } from '../firebase';

interface DocumentViewerProps {
  resultId: string;
  onClose: () => void;
  personaName: string;
}

type DownloadFormat = 'html' | 'pdf' | 'doc' | 'png';

export function DocumentViewer({
  resultId,
  onClose,
  personaName,
}: DocumentViewerProps) {
  const [mode, setMode] = useState<'card' | 'full'>('card');
  const [downloadOpen, setDownloadOpen] = useState(false);
  const [downloading, setDownloading] = useState<DownloadFormat | null>(null);
  const [doc, setDoc] = useState<{ content: string; fileType: string; tool_name: string } | null>(null);
  const [loading, setLoading] = useState(true);
  const previewRef = useRef<HTMLIFrameElement>(null);

  const title = doc?.tool_name || 'Document';

  useEffect(() => {
    (async () => {
      try {
        const data = await fetchToolResult(resultId);
        if (data) {
          setDoc({
            content: data.content,
            fileType: data.file_type,
            tool_name: data.tool_name
          });
        }
      } catch (err) {
        console.error("Failed to load result:", err);
      } finally {
        setLoading(false);
      }
    })();
  }, [resultId]);
  const captureRef = useRef<HTMLDivElement>(null);

  const handleDownloadBlob = useCallback((blob: Blob, ext: string, mime: string) => {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${title.replace(/\s+/g, '-').toLowerCase()}${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }, [title]);

  const downloadAs = useCallback(async (format: DownloadFormat) => {
    if (!doc) return;
    const { content } = doc;
    setDownloading(format);
    setDownloadOpen(false);

    try {
      // ── HTML download ──
      if (format === 'html') {
        const blob = new Blob([content], { type: 'text/html' });
        handleDownloadBlob(blob, '.html', 'text/html');
        setDownloading(null);
        return;
      }

      // ── DOC download (Word-compatible HTML) ──
      if (format === 'doc') {
        const docHtml = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body { font-family: 'Calibri', 'Arial', sans-serif; font-size: 12pt; line-height: 1.6; color: #000; max-width: 800px; margin: 40px auto; padding: 0 20px; }
  h1 { font-size: 22pt; color: #1a1a1a; border-bottom: 2px solid #d0a78b; padding-bottom: 8px; }
  h2 { font-size: 16pt; color: #333; margin-top: 24px; }
  p { margin: 8px 0; }
  ul, ol { margin: 8px 0; padding-left: 24px; }
  li { margin: 4px 0; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  td, th { border: 1px solid #ccc; padding: 8px; text-align: left; }
  th { background: #f5f5f5; }
  blockquote { border-left: 3px solid #d0a78b; margin: 12px 0; padding: 8px 16px; background: #fafafa; }
  hr { border: none; border-top: 1px solid #e0e0e0; margin: 24px 0; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 9pt; color: #888; text-align: center; }
</style>
</head>
<body>
${content.replace(/<!DOCTYPE html>[\s\S]*?<body[^>]*>/i, '').replace(/<\/body>[\s\S]*?<\/html>/i, '')}
<div class="footer">Generated by ${personaName} · Eburon AI</div>
</body>
</html>`;
        const blob = new Blob([docHtml], { type: 'application/msword' });
        handleDownloadBlob(blob, '.doc', 'application/msword');
        setDownloading(null);
        return;
      }

      // ── PDF / PNG — capture the iframe content via html2canvas ──
      const iframe = previewRef.current;
      if (!iframe) { setDownloading(null); return; }

      const { default: html2canvas } = await import('html2canvas');

      // Render the content in a temporary offscreen container for clean capture
      const temp = document.createElement('div');
      temp.innerHTML = content;
      temp.style.cssText = 'position:fixed;left:-9999px;top:0;width:794px;background:#fff;font-size:16px;line-height:1.6;color:#000;padding:40px;font-family:system-ui,sans-serif';
      // Inject any linked styles from the original content
      const styleTags = temp.querySelectorAll('style, link[rel="stylesheet"]');
      // Ensure all style is inline for capture
      document.body.appendChild(temp);

      try {
        const canvas = await html2canvas(temp, {
          scale: 2,
          useCORS: true,
          allowTaint: true,
          backgroundColor: '#ffffff',
          width: 794,
          height: temp.scrollHeight,
          windowWidth: 794,
          windowHeight: temp.scrollHeight,
        });

        document.body.removeChild(temp);

        if (format === 'png') {
          canvas.toBlob((blob) => {
            if (blob) handleDownloadBlob(blob, '.png', 'image/png');
          }, 'image/png');
          setDownloading(null);
          return;
        }

        if (format === 'pdf') {
          const { default: jsPDF } = await import('jspdf');
          const imgData = canvas.toDataURL('image/png');
          const imgWidth = 210; // A4 width in mm
          const imgHeight = (canvas.height * imgWidth) / canvas.width;
          const pdf = new jsPDF('p', 'mm', 'a4');
          let heightLeft = imgHeight;
          let position = 0;

          pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
          heightLeft -= 297; // A4 height in mm

          while (heightLeft > 0) {
            position = heightLeft - imgHeight; // negative offset for next page
            pdf.addPage();
            pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
            heightLeft -= 297;
          }

          pdf.save(`document.pdf`);
          setDownloading(null);
        }
      } catch (err) {
        document.body.removeChild(temp);
        console.error('Capture failed:', err);
        setDownloading(null);
      }
    } catch (err) {
      console.error('Download failed:', err);
      setDownloading(null);
    }
  }, [doc, personaName, handleDownloadBlob]);

  const openFullPreview = () => {
    if (!doc) return;
    if (doc.fileType !== 'html') {
      const blob = new Blob([doc.content], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank');
      return;
    }
    setMode('full');
  };

  const downloadOptions: { format: DownloadFormat; label: string; icon: typeof FileText }[] = [
    { format: 'html', label: 'HTML', icon: FileText },
    { format: 'pdf', label: 'PDF', icon: FileText },
    { format: 'doc', label: 'DOC', icon: FileText },
    { format: 'png', label: 'PNG Image', icon: Image },
  ];

  // ── Full page preview mode ──
  if (mode === 'full') {
    if (loading || !doc) return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black"><Loader2 className="w-8 h-8 text-white animate-spin" /></div>;

    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="fixed inset-0 z-50 bg-black flex flex-col"
      >
        {/* Minimal header */}
        <header className="flex items-center justify-between px-5 py-3 bg-zinc-900/90 border-b border-zinc-800/60 shrink-0">
          <div className="flex items-center gap-3 min-w-0">
            <button
              onClick={() => setMode('card')}
              className="p-2 rounded-lg text-zinc-500 hover:text-[#d0a78b] hover:bg-zinc-800/60 transition-all shrink-0"
              aria-label="Back"
              title="Back"
            >
              <X className="w-4 h-4" />
            </button>
            <div className="min-w-0">
              <p className="text-sm font-medium text-zinc-200 truncate">Document Preview</p>
              <p className="text-[9px] text-zinc-500 uppercase tracking-widest">live preview</p>
            </div>
          </div>

          {/* Download dropdown */}
          <div className="relative">
            <button
              onClick={() => setDownloadOpen(!downloadOpen)}
              disabled={!!downloading}
              className="flex items-center gap-2 px-4 py-2 rounded-xl bg-[#d0a78b] text-black text-sm font-semibold hover:bg-[#ebd0bc] transition-all active:scale-[0.97] disabled:opacity-60"
            >
              {downloading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  {downloading.toUpperCase()}
                </>
              ) : (
                <>
                  <FileDown className="w-4 h-4" />
                  Download as
                  <ChevronDown className={`w-3.5 h-3.5 transition-transform ${downloadOpen ? 'rotate-180' : ''}`} />
                </>
              )}
            </button>

            {downloadOpen && !downloading && (
              <>
                <div className="fixed inset-0 z-40" onClick={() => setDownloadOpen(false)} />
                <div className="absolute right-0 top-full mt-1.5 z-50 bg-zinc-900 border border-zinc-700/60 rounded-xl overflow-hidden shadow-2xl shadow-black/40 min-w-[160px]">
                  {downloadOptions.map((opt) => (
                    <button
                      key={opt.format}
                      onClick={() => downloadAs(opt.format)}
                      className="w-full flex items-center gap-3 px-4 py-2.5 text-sm text-zinc-300 hover:text-white hover:bg-zinc-800/80 transition-colors text-left"
                    >
                      <opt.icon className="w-4 h-4 text-zinc-500" />
                      {opt.label}
                    </button>
                  ))}
                </div>
              </>
            )}
          </div>
        </header>

        {/* Full-bleed live preview */}
        <div className="flex-1 bg-white relative overflow-hidden">
          <iframe
            ref={previewRef}
            srcDoc={doc.fileType === 'html' ? doc.content : `<pre style="font-family:monospace;white-space:pre-wrap;padding:20px;font-size:14px;color:#000;background:#fff">${doc.content.replace(/</g, '&lt;')}</pre>`}
            className="absolute inset-0 w-full h-full border-0"
            sandbox="allow-scripts"
            title="Live Document Preview"
          />
        </div>
      </motion.div>
    );
  }

  // ── Card mode (initial view) ──
  if (loading || !doc) return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80"><Loader2 className="w-8 h-8 text-white animate-spin" /></div>;

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 bg-[#050505] flex flex-col h-[100dvh]"
    >
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_30%,rgba(208,167,139,0.04),transparent_70%)] pointer-events-none" />

      {/* Header */}
      <header className="sticky top-0 w-full bg-[#050505]/95 backdrop-blur-md border-b border-zinc-800/60 px-4 py-3 flex items-center justify-between z-10 shrink-0">
        <button
          onClick={onClose}
          className="p-2 rounded-lg text-zinc-500 hover:text-[#d0a78b] hover:bg-zinc-850/50 transition-all"
          aria-label="Close"
          title="Close"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="text-center flex flex-col items-center">
          <h1 className="text-sm font-semibold tracking-wide text-[#d0a78b]">Document Workspace</h1>
          <p className="text-[9px] text-zinc-500 tracking-[0.2em] lowercase -mt-0.5">preview mode</p>
        </div>

        <div className="w-9" />
      </header>

      {/* Content */}
      <div className="flex-1 overflow-y-auto px-4 py-6 max-w-5xl mx-auto w-full flex flex-col justify-between">
        {/* Document Card */}
        <div className="bg-zinc-900/40 border border-zinc-800/80 rounded-[24px] overflow-hidden flex flex-col min-h-[400px]">
          <div className="flex items-center gap-3 px-5 py-4 border-b border-zinc-800/40 bg-zinc-900/60">
            <div className="w-10 h-10 rounded-xl bg-[#d0a78b]/10 flex items-center justify-center">
              <FileText className="w-5 h-5 text-[#d0a78b]" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-zinc-200 truncate">Result</p>
              <p className="text-[10px] text-zinc-500 uppercase tracking-wider">
                {doc.fileType === 'html' ? 'Web Document' : 'Text File'}
              </p>
            </div>
          </div>

          {/* Live Preview — ALWAYS shown, no source code toggle */}
          <div className="flex-1 min-h-[350px] bg-white relative">
            <iframe
              srcDoc={doc.fileType === 'html' ? doc.content : `<pre style="font-family:monospace;white-space:pre-wrap;padding:20px;font-size:14px;color:#000;background:#fff">${doc.content.replace(/</g, '&lt;')}</pre>`}
              className="absolute inset-0 w-full h-full border-0"
              sandbox="allow-scripts"
              title="Document Preview"
            />
          </div>
        </div>

        {/* Open Now button */}
        <button
          onClick={openFullPreview}
          className="mt-5 w-full flex items-center justify-center gap-2 px-5 py-3.5 rounded-xl bg-[#d0a78b] text-black text-sm font-semibold hover:bg-[#ebd0bc] transition-all shadow-lg shadow-[#d0a78b]/10 active:scale-[0.98]"
        >
          <ExternalLink className="w-4 h-4" />
          Open Now
        </button>
      </div>
    </motion.div>
  );
}
